### ISSUE TITLE
Error team in use

### ISSUE THREAD

**Issue by Joansitoh** [bizarre/Azazel#11]
`[Server] INFO java.lang.IllegalArgumentException: Team name '' is already in use
02.06 02:11:36 [Server] INFO at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[mSpigot.jar:git-PaperSpigot-dc772289]
02.06 02:11:36 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scoreboard.CraftScoreboard.registerNewTeam(CraftScoreboard.java:140) ~[mSpigot.jar:git-PaperSpigot-dc772289]
02.06 02:11:36 [Server] INFO at com.bizarrealex.azazel.tab.Tab.<init>(Tab.java:36) ~[?:?]
02.06 02:11:36 [Server] INFO at com.bizarrealex.azazel.Azazel$1.run(Azazel.java:76) ~[?:?]
02.06 02:11:36 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[mSpigot.jar:git-PaperSpigot-dc772289]`

**Comment by bizarre** [comment]
Steps to reproduce, server version, client version, screenshot
